sudo: required
services:
  - docker 

  before_install:
    - docker build -t dshendocer209/docker-react -f Dockerfile.dev . 

  script:
    - docker run dshendocer209/docker-react npm run test -- --coverage